services:
  xybotv2:
    image: henryxiaoyang/xybotv2:latest
    container_name: XYBotV2
    restart: on-failure:3
    ports:
      - "9999:9999"  # 映射gunicorn端口
    volumes:
      - redis_data:/var/lib/redis

volumes:
  redis_data:
    name: redis_data