[WechatAPIServer]
port = 9000
mode = "release"
redis-host = "localhost"
redis-port = 6379
redis-password = ""
redis-db = 0

[XYBot]
version = "v1.0.0"
ignore-protection = false
XYBotDB-url = "sqlite:///database/xybot.db"
msgDB-url = "sqlite+aiosqlite:///database/message.db"
keyvalDB-url = "sqlite+aiosqlite:///database/keyval.db"
admins = [ "admin-wxid", "admin-wxid",]
disabled-plugins = [ "ExamplePlugin", "TencentLke", "DailyBot",]
timezone = "Asia/Shanghai"
auto-restart = false

[WebInterface]
enable = true
port = 8080
host = "0.0.0.0"
debug = false
username = "admin"
password = "admin123"

[Notification]
enable = true
pushplus-token = ""
notify-online = true
notify-offline = true
online-title = "机器人已上线"
offline-title = "机器人已掉线"
ignore-mode = "None"
whitelist = [ "wxid_1", "wxid_2", "111@chatroom", "222@chatroom",]
blacklist = [ "wxid_3", "wxid_4", "333@chatroom", "444@chatroom",]
